spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ 你的项目使用的数据库名
    username: 你的数据库用户名
    password: 你的数据库密码
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.qq.com
    username: 你的QQ邮箱
    password: 你的QQ邮箱授权码
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true